project_name: revealgo
before:
  hooks:
  - git submodule update --init --recursive
build:
  binary: revealgo
  main: cmd/revealgo/reveal.go
  ldflags:
  - -s -w -X github.com/yusukebe/revealgo.Version=v{{.Version}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: windows
      goarch: arm
  env:
    - CGO_ENABLED=0
archives:
- name_template: "{{.Binary}}_{{ .Version }}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
  - LICENSE
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
release:
  draft: true
  prerelease: auto
